### ISSUE TITLE
首页 › MySQL查询 › 库表业务组 › 增加 库表业务组 中“映射的mysql用户:”添加报错403 Forbidden

### ISSUE THREAD

**Issue by WilliamGuozi** [lazzyfu/AuditSQL#187]
2019-05-22 14:48:31,344 [uWSGIWorker4Core0:140672907941952] [django.request:228] [log:log_response] [WARNING]- Forbidden (Permission denied): /admin/query/mysqlusergroupmap/add/
Traceback (most recent call last):
  File "/venv_py36/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/venv_py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/venv_py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv_py36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/venv_py36/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/venv_py36/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/venv_py36/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/venv_py36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1637, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/venv_py36/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/venv_py36/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/venv_py36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/venv_py36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1542, in _changeform_view
    raise PermissionDenied
django.core.exceptions.PermissionDenied

**Comment by lazzyfu** [comment]
请确保django连接本地数据库的账号具有with grant options权限
# 配置MySQL数据库，库必须先创建，且库的字符集必须为:utf8
# 存储django程序运行的系统库表等数据
# 权限：grant all on *.* to 'xxx'@'xxxhost' with grant options

**Comment by WilliamGuozi** [comment]
![image](https://user-images.githubusercontent.com/30142292/58156502-cac88680-7ca8-11e9-9337-660226ac91b3.png)

![image](https://user-images.githubusercontent.com/30142292/58156405-90f78000-7ca8-11e9-84b9-e49a06be683f.png)

**Comment by WilliamGuozi** [comment]
字符集和权限应该是正确的

**Comment by lazzyfu** [comment]
加群讨论，谢谢

**Comment by WilliamGuozi** [comment]
OK
